workflow:
  rules:
    - if: $CI_COMMIT_BRANCH 

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

stages:
# At first debian : init variables
- quality 
- build-debian
- create-debian-package
- test-publish-debian
- Docker-hub-build
- Docker-hub-test
- Docker-hub-pushtag

### All
- build
- create-package
- test-publish

hadolint:
  image: hadolint/hadolint:latest-debian
  before_script:
    - cd $CI_PROJECT_DIR 
  script:
    - ls -la
    - hadolint gitlabci/docker-ci/Dockerfile 
  stage: quality

include:
  - 'gitlabci/docker-hub.yml'
  - 'gitlabci/debianlatest.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
