workflow:
  rules:
    - if: $CI_COMMIT_BRANCH 

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

stages:
# At first debian : init variables

- valid
- build-debian
- create-debian-package
- test-publish-debian
- Docker-hub-build
- Docker-hub-test
- Docker-hub-pushtag

### All
- build
- create-package
- test-publish

lint:hadolint:
  image: hadolint/hadolint:latest
  only:
    refs:
      - branches
  script: hadolint gitlabci/docker-ci/Dockerfile 
  stage: valid

include:
  - 'gitlabci/docker-hub.yml'
  - 'gitlabci/debianlatest.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
