workflow:
  rules:
    - if: $CI_COMMIT_BRANCH 

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

stages:
# At first debian : init variables
- quality 
- build-debian
- create-debian-package
- test-publish-debian
# AMD64 docker
- Docker-hub-build
- Docker-hub-test
- Docker-hub-pushtag
# ARM docker
- Docker-hub-build-arm
- Docker-hub-test-arm
- Docker-hub-pushtag-arm

### All
- build
- create-package
- test-publish

hadolint:
  image: hadolint/hadolint:latest-debian
  before_script:
    - cd $CI_PROJECT_DIR 
  script:
    - hadolint --ignore DL3008 gitlabci/docker-ci/Dockerfile 
    - hadolint --ignore DL3008 gitlabci/docker-ci/Dockerfile-arm 
  stage: quality

include:
  - 'gitlabci/docker-hub-arm.yml'
  - 'gitlabci/docker-hub.yml'
  - 'gitlabci/debianlatest.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbian.yml'
  - 'gitlabci/ubuntufocal.yml'
