stages:
# At first : init variables
- build:debian
- create-debian-package
- TestDebian
- ubuntufocal
- ubuntubionic
- create-ubuntu-packagebionic
- Testubuntubionic
- build:raspbian
- create-raspbian-package
#

include:
  - 'gitlabci/debianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
