stages:
- build:debian
- create-debian-package
- TestDebian
- ubuntubionic
- create-ubuntu-packagebionic
- Testubuntubionic
- ubuntufocal
- build:raspbian
- create-raspbian-package
#

include:
  - 'gitlabci/debianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspianbuster.yml'
