stages:
# At first debian : init variables
- builddebian
- build
- create-debian-package
- testdebian
  #- ubuntubionic
- create-ubuntu-packagebionic
- testubuntubionic
  #- ubuntufocal
- create-ubuntu-packagefocal
- testubuntufocal
  #- build:raspbian
- create-raspbian-package

makedebian:
  stage: builddebian
  artifacts:
   expire_in: 20 minutes
   paths:
    - /builds/fredbcode/e2guardian
  image: amd64/debian:stable
  variables:
    OS: "debian"
  script:
    - apt update
    - apt-get -y upgrade
    - apt install --no-install-recommends --no-install-suggests -y curl unzip base-files automake base-passwd
      bash coreutils dash debianutils diffutils dpkg e2fsprogs findutils grep gzip hostname ncurses-base
      libevent-pthreads-* libevent-dev ncurses-bin perl-base sed login sysvinit-utils tar bsdutils
      mount util-linux libc6-dev libc-dev gcc g++ make dpkg-dev autotools-dev debhelper dh-autoreconf dpatch
      libclamav-dev libpcre3-dev zlib1g-dev pkg-config libssl-dev libssl1.1 git ca-certificates lsb-release
    - cd /builds/fredbcode/e2guardian && ./autogen.sh && ./configure  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'
    - make
    - find /builds/ -name ".git" -exec rm -r "{}" +

include:
  - 'gitlabci/debianbuster.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
