cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
stages:
# At first debian : init variables
- build-debian
- create-debian-package
- test-publish-debian
###
- build
- create-package
- test-publish
  #- ubuntubionic
  #- create-ubuntu-packagebionic
  #- testubuntubionic
  #- ubuntufocal
  #- create-ubuntu-packagefocal
  #- testubuntufocal
  #- build:raspbian
  #- create-raspbian-package

include:
  - 'gitlabci/debianbuster.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
