stages:
# At first debian : init variables
- builddebian
- build
- create-debian-package
- testdebian
  #- ubuntubionic
- create-ubuntu-packagebionic
- testubuntubionic
  #- ubuntufocal
- create-ubuntu-packagefocal
- testubuntufocal
  #- build:raspbian
- create-raspbian-package

include:
  - 'gitlabci/debianbuster.yml'
  - 'gitlabci/ubuntubionic.yml'
  - 'gitlabci/raspbianbuster.yml'
  - 'gitlabci/ubuntufocal.yml'
